MAKE="make -f Makefile.dkms"
CLEAN="make -f Makefile.dkms clean"
BUILT_MODULE_NAME=firewall
BUILT_MODULE_LOCATION=src/kernel-module
DEST_MODULE_LOCATION=/updates/dkms
PACKAGE_NAME=linux-firewall-kmod
PACKAGE_VERSION=#MODULE_VERSION#
AUTOINSTALL=yes